import LayoutControls from "./LayoutControls.jsx";
import PrintControls from "./PrintControls.jsx";
import BorderControls from "./BorderControls.jsx";
import PhotoControls from "./PhotoControls.jsx";

function ControlPanel({
  baseLayouts,
  computeGrid,
  pageOrientation,
  selectedLayout,
  setSelectedLayout,
  pxToMm,
  customWidthMm,
  setCustomWidthMm,
  customHeightMm,
  setCustomHeightMm,
  customColumns,
  setCustomColumns,
  customRows,
  setCustomRows,
  customGapMm,
  setCustomGapMm,
  GAP_MIN_MM,
  GAP_MAX_MM,
  grid,
  rotatePage,
  copies,
  setCopies,
  setA4Pages,
  images,
  totalPrints,
  a4Pages,
  borderEnabled,
  setBorderEnabled,
  BORDER_MIN_MM,
  BORDER_MAX_MM,
  BORDER_STEP_MM,
  borderWidthMm,
  setBorderWidthMm,
  borderSliderFillPct,
  borderRounded,
  setBorderRounded,
  borderRadiusMm,
  setBorderRadiusMm,
  borderRadiusSliderFillPct,
  isDragging,
  setIsDragging,
  handleDrop,
  handleUpload,
  clearAllImages,
  generatePDF,
  isDownloading,
}) {
  return (
    <aside className="panel">
      <LayoutControls
        baseLayouts={baseLayouts}
        computeGrid={computeGrid}
        pageOrientation={pageOrientation}
        selectedLayout={selectedLayout}
        setSelectedLayout={setSelectedLayout}
        pxToMm={pxToMm}
        customWidthMm={customWidthMm}
        setCustomWidthMm={setCustomWidthMm}
        customHeightMm={customHeightMm}
        setCustomHeightMm={setCustomHeightMm}
        customColumns={customColumns}
        setCustomColumns={setCustomColumns}
        customRows={customRows}
        setCustomRows={setCustomRows}
        customGapMm={customGapMm}
        setCustomGapMm={setCustomGapMm}
        GAP_MIN_MM={GAP_MIN_MM}
        GAP_MAX_MM={GAP_MAX_MM}
        grid={grid}
      />
      <PrintControls
        pageOrientation={pageOrientation}
        rotatePage={rotatePage}
        copies={copies}
        setCopies={setCopies}
        setA4Pages={setA4Pages}
        images={images}
        totalPrints={totalPrints}
        a4Pages={a4Pages}
      />
      <BorderControls
        pxToMm={pxToMm}
        grid={grid}
        borderEnabled={borderEnabled}
        setBorderEnabled={setBorderEnabled}
        BORDER_MIN_MM={BORDER_MIN_MM}
        BORDER_MAX_MM={BORDER_MAX_MM}
        BORDER_STEP_MM={BORDER_STEP_MM}
        borderWidthMm={borderWidthMm}
        setBorderWidthMm={setBorderWidthMm}
        borderSliderFillPct={borderSliderFillPct}
        borderRounded={borderRounded}
        setBorderRounded={setBorderRounded}
        borderRadiusMm={borderRadiusMm}
        setBorderRadiusMm={setBorderRadiusMm}
        borderRadiusSliderFillPct={borderRadiusSliderFillPct}
        setA4Pages={setA4Pages}
      />
      <PhotoControls
        isDragging={isDragging}
        setIsDragging={setIsDragging}
        handleDrop={handleDrop}
        handleUpload={handleUpload}
        images={images}
        clearAllImages={clearAllImages}
        generatePDF={generatePDF}
        isDownloading={isDownloading}
      />
    </aside>
  );
}

export default ControlPanel;
